In [3]:
# settings local:
%run "../../../common/0_notebooks_base_setup.py"   

c:\Users\fpeloso\Digital House\Prácticas mías\Practica-de-Clases\clase_03\dsad_2021\common
default checking
Running command `conda list`... ok
jupyterlab=2.2.6 already installed
pandas=1.1.5 already installed
bokeh=2.2.3 already installed
seaborn=0.11.0 already installed
matplotlib=3.3.2 already installed
ipywidgets=7.5.1 already installed
pytest=6.2.1 already installed
chardet=4.0.0 already installed
psutil=5.7.2 already installed
scipy=1.5.2 already installed
statsmodels=0.12.1 already installed
scikit-learn=0.23.2 already installed
xlrd=2.0.1 already installed
Running command `conda install --yes nltk=3.5.0`... ok
Solving environment: ...working... done

# All requested packages already installed.


unidecode=1.1.1 already installed
pydotplus=2.0.2 already installed
pandas-datareader=0.9.0 already installed
flask=1.1.2 already installed


---

<img src='../../../common/logo_DH.png' align='left' width=35%/>


En la práctica de la clase de hoy usaremos un dataset de Kaggle que tiene datos de ventas:

https://www.kaggle.com/kyanyoga/sample-sales-data

Ustedes tienen un subconjunto de los datos disponibles, que usaremos para resolver ejercicios de Numpy.

## Ejercicio 1

Leer los datos del archivo /M1/CLASE_03_Numpy/Data/sales_data_sample_excercise.csv

Este archivo tiene algunos datos numéricos y otros de tipo cadena de caracteres. 

Las columnas son:

* ORDERNUMBER: int, id de la orden

* SALES: float, monto abonado

* MONTH_ID: int, mes

* YEAR_ID: int, año

* PRODUCTLINE: str, producto

* COUNTRY: str, país de venta

¿Recuerdan que todos los elementos de una instancia de ndarray deben ser del mismo tipo? Entonces vamos a leer el archivo y crear una instancia de ndarray de tipo cadena de caracteres.

¿Qué pasaría si intentáramos crear una instancia de tipo int? ¿Y de tipo float?


In [4]:
import numpy as np

# local:
data_location = '../Data/sales_data_sample_excercise.csv'

#datos=np.genfromtxt(data_location,delimiter='\t', dtype=str)

## Ejercicio 2

Crear un array numérico que tenga como valores las columna SALES y otro array de str que tenga como valores la columna COUNTRY

Ayuda: https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.astype.html

In [5]:
datos = np.genfromtxt(data_location, skip_header=1, delimiter='\t', dtype= str)

ventas_vector_str = datos[:, 1]
ventas_vector =  ventas_vector_str.astype(np.float)
print(ventas_vector)

paises_vector = datos[:, 5]
print(paises_vector)


[2871.   2765.9  3884.34 ... 5417.57 2116.16 3079.44]
['USA' 'France' 'France' ... 'Spain' 'France' 'USA']


## Ejercicio 3

¿Cuál fue el monto mínimo de una venta? ¿Cuál fue el monto máximo?

In [6]:
print(np.min(ventas_vector))
print(np.max(ventas_vector))

482.13
14082.8


## Ejercicio 4

¿Cuántas ventas se hicieron en Spain?

Ayuda: boolean indexing


In [7]:
mask=paises_vector =='Spain'
españa_ventas=paises_vector[mask]
np.size(españa_ventas)

342

## Ejercicio 5

¿Qué porcentaje de las ventas se hicieron en Spain?


In [8]:
#print(np.size(españa_ventas)/np.size(paises_vector))
total_españa=np.sum(ventas_vector[mask])
total_ventas=np.sum(ventas_vector)

print(total_españa/total_ventas)


0.12117331740025447


## Ejercicio 6

¿Cuál es el país de la venta de precio máximo? ¿Cuál es el id de esa venta?

Ayuda: boolean indexing

In [9]:
precio_max=np.max(ventas_vector)
mask2=ventas_vector==precio_max

print(paises_vector[mask2])

ID_vector_str = datos[:, 0]

print(ID_vector_str[mask2])


['USA']
['10407']


## Ejercicio 7

¿Cuál es el precio promedio de ventas en France? ¿Cuál es el desvío?

In [10]:
maskF= paises_vector =='France'
francia_ventas=ventas_vector[maskF]

print(np.mean(francia_ventas))
print(np.std(francia_ventas))

3537.9507006369427
1939.214360481481


## Ejercicio 8

¿Cuál fue el año con máximo desvío en las ventas en France?

Ayuda: https://docs.scipy.org/doc/numpy/reference/generated/numpy.unique.html

In [48]:
#en francia_ventas tengo todos los años, tengo que separar en distintos vectores 
#mascara donde esta francia
data_france_mask = paises_vector == 'France'
#aplico mascara al vector de ventas
data_france_sales = datos[data_france_mask, 1]
#aplico mascara al vector de años
data_france_years = datos[data_france_mask, 3]

#convierto los años en numeros
data_france_years_num = data_france_years.astype(np.int)

#me devuelve los valores unicos de años
years_unique = np.unique(data_france_years_num)
print(years_unique)

#crea una lista vacia
desvios = []
#recorro cada año en la lista de años unicos
for year in years_unique:
    #creo una mascara para cada año
    years_vector_mask = data_france_years_num == year
    #aplico la mascara de dicho año al vector de ventas
    precios_year_mask = data_france_sales[years_vector_mask].astype(np.float)    
    #calculo el desvio del vector que tiene todas las ventas de dicho año
    desvio_year = precios_year_mask.std()
    #guardo el resultado del desvio en la lista vacia
    desvios.append(desvio_year)

print(desvios)

#calculo el desvio max en la lista de tres desvios, uno para cada año
desvio_max = np.array(desvios).max()
#crea una mascara de la lista de desvios, donde es true cuando el desvio es maximo
desvios_max_mask = desvios == desvio_max
#aplico dicha mascara al vector de años unicos
year_desvio_max = years_unique[desvios_max_mask]
print(year_desvio_max)
print(type(year_desvio_max))    


[2003 2004 2005]
[1860.7718844747073, 1837.8438485766644, 2241.7723043613423]
[2005]
<class 'numpy.ndarray'>


In [54]:
a=np.arange(15)

maska= a>=5
maskb= a<=11
maskc=np.logical_and(maska,maskb)
print(a[maskc])

print(a)

[ 5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
