## Incluye Módulos 1 - 2 - 3

Voy a hacer un repaso de lo visto en las Clases 3 del Primer Módulo

#### Clase 3 - Numpy

In [1]:
import numpy as np

In [6]:
#creo una lista
ejemplo_lista=[1,2,3,4,5]

#con la lista creo un array
ejemplo_array=np.array(ejemplo_lista)

print(ejemplo_array)
type(ejemplo_array)

[1 2 3 4 5]


numpy.ndarray

In [7]:
#metodo empty
#la paso una tupla con las dimensiones que quiero y luego el tipo de variable 
# que quiero que sea
np.empty((2,2),dtype=int)

array([[ 1626753975,  -544657015],
       [ -717176970, -1628072401]])

In [8]:
np.empty((1,3),dtype=float)

array([[9.06619155e-312, 0.00000000e+000, 1.44638204e-307]])

In [9]:
np.empty((3,1),dtype=bool)

array([[ True],
       [False],
       [ True]])

In [13]:
np.zeros(5,dtype=float)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((2,3),dtype=str)

array([['', '', ''],
       ['', '', '']], dtype='<U1')

In [15]:
np.ones((1,2),dtype=int)

array([[1, 1]])

In [20]:
#Ejemplo de generación de numeros aleatorios
random_generator=np.random.default_rng()

#cuando invoco al default_rng ("aca puedo pasar las semilla")

array_3D=random_generator.normal(0,1,(2,3))

In [21]:
array_3D.shape

(2, 3)

In [22]:
array_3D.ndim

2

#### Slicing
Poner ejemplos

In [23]:
#Indexin [start:stop:step]
#Fancy Indexing
#Boolean Indexing